#ifndef _SYSCALLS_H
#define _SYSCALLS_H

enum {
    SYSCALL_SERIAL_NWRITE = 0,
    SYSCALL_SERIAL_READ,
    SYSCALL_BTN_STATES,
    SYSCALL_SWTCH_STATES,
    SYSCALL_POT_VALUE,
};

#endif /* _SYSCALLS_H */